name: containerize

on:
  workflow_dispatch:

jobs:
  containerize-app:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v4
      with:
        repository: arandombit/hydra
        token: ${{ secrets.GITHUB_TOKEN }}
